version: "3.9"
services:
  first:
    container_name: pocPython
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - poc
    volumes:
        - .:/code

    ports:
      - 5000:80
